add_newline = false
format = "$directory> "
right_format = "$status$cmd_duration$git_branch${custom.git_status_dirty}$git_status"

[directory]
style = "fg:#FFFFFF"
format = "[C:/$path]($style)"
home_symbol = "home/victor"

[python]
format = '\($virtualenv\) '

[cmd_duration]
format = ' [$duration]($style)'

[git_branch]
format = ' [$branch]($style)'
style = 'green'

[git_status]
format = '( [\[$all_status$ahead_behind$stashed\]]($style))'
style = "red"
stashed = "≡"
ahead = "⇡${count}"
behind = "⇣${count}"

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'
